config/routes.rb
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get     'sessions/new'
  post    'sessions/create'
  delete  'sessions/destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  get '/index', to: 'posts#index'
  get    '/posts',   to: 'posts#new'
  post   '/posts',   to: 'posts#create'
  get     'posts/new'
  post    'posts/create'

  root 'static_pages#home'
  get   '/home',        to: 'static_pages#home'
  get   '/help',        to: 'static_pages#help'
  get   '/about',       to: 'static_pages#about'
  get   '/contact',     to: 'static_pages#contact'
  get   '/signup',      to: 'users#new'
  post  '/signup',      to: 'users#create'
  get   '/edit',        to: 'users#update'

end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
 <!--Footer-->
<footer class="container footer">
  <nav class="navbar d-flex">
    <ul>
      <li>ABOUT US
      </li>
      <li>SUPPORT</li>
      <li>PRESS</li>
      <li>API</li>
      <li>JOBS</li>
      <li>PRIVACY</li>
      <li>TERMS</li>
      <li>DIRECTORY</li>
      <li>PROFILES</li>
      <li>HASHTAGS</li>
      <li>LANGUAGE</li>
    </ul>
    <p> © 2019 FILMY </p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<head>
  <title>Filmy</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_introduction.html.erb
<header class=" text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <a href="users/new" class="btn btn-primary btn-xl rounded-pill mt-5">Sign up now</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="assets/01.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Lưu lại ký ức bỏ quên</h2>
          <p>Filmy sẽ là một cuốn nhật ký nhỏ nơi từng khoảnh khắc được lưu lại sau những bức ảnh. Thật ý nghĩa nếu kèm theo một câu chuyện với nó</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="assets/02.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Dễ dàng chia sẻ</h2>
          <p>Kết nối với tất cả mọi người có cùng đam mê chụp ảnh film trên toàn thế giới</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="assets/03.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Viết tất cả những gì bạn muốn</h2>
          <p>Gợi lại một phần của ký ức với trang blog của bạn. Viết mọi thứ mà bạn muốn chia sẻ với tất cả mọi người</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navigation.html.erb
<!--Navigation Bar-->
<nav class="navbar navbar-light bg-light d-flex">
  <div class="container">
    <div class="logo">
    <%if logged_in?%>
      <a class="navbar-brand" href="/index">
      <i class="fa fa-camera-retro" aria-hidden="true"></i>
        Filmy
      </a>
    <%else%>
      <a class="navbar-brand" href="/#root">
      <i class="fa fa-camera-retro" aria-hidden="true"></i>
        Filmy
      </a>
    <%end%>
    </div>
    <div class="m-auto">
      <form class="form-inline search-form">
        <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
      </form>
    </div>

    <div class="user-section">
      <a><i class="fa fa-compass" ></i></a>

      <% if logged_in? %>

      <a class="navbar-brand" href="<%= posts_path%>">
        <i class="fa fa-upload"></i>
      </a>

      <a class="navbar-brand" href="<%= user_path(current_user)%>">
        <i class="fa fa-user" aria-hidden="true"></i>
      </a>

      <% else %>
        <a class="navbar-brand" href="/sessions/new">
      <i class="fa fa-user" aria-hidden="true"></i>
      </a>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <%= render 'layouts/header' %>
  <body>
  <%=render 'layouts/navigation'%>
  <%flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <%end%>
    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

   <%= render 'layouts/footer' %>
  </body>
</html>